server:
  port: 38550

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug



spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true